### ISSUE TITLE
Allow integers for `msk_alpha` in `plot_image`

### ISSUE THREAD

**Issue by silvbarb** [fmicompbio/ez_zarr#15]
Currently when passing `msk_alpha` = 0 we get a Type error as we enforce a float. 
I think we could accept integers as well

**Comment by mbstadler** [comment]
`msk_alpha` is now explicetly converted to `float()` when passing it to `matplotlib.pyplot.imshow`, which should avoid this issue (will be part of release v0.3.1). I am closing the issue now, but feel free to open it again if that should not fix your test case.
