### ISSUE TITLE
Allow for inferno-like palettes for single channel images in plot_image()

### ISSUE THREAD

**Issue by silvbarb** [fmicompbio/ez_zarr#24]
For inspection of single stainings, it can be quite useful to use a perceptually uniform color palette from matplotlib, like inferno, instead of different intensities of an RGB color (https://matplotlib.org/stable/users/explain/colors/colormaps.html)

Currently we enforce the conversion of the image to RGB, thereby preventing the usual behavior of the matplotlib 'cmap' argument. 

What do you think?

**Comment by mbstadler** [comment]
This has been added in [e5959ae](https://github.com/fmicompbio/ez_zarr/commit/e5959ae784f6064a1ba65e17c066fa4c9b721848)
